java-racingcar 1.0
piedra-de-flor/java-racingcar pull request #1
Opened 2023-06-17 12:10 UTC by piedra-de-flor

2023-06-18 00:18 UTC, graygreat requested changes
안녕하세요 영우님~
코드 짤 때, 많은 고민을 하신게 느껴지네요 ㅎ

몇 가지 리뷰 남겨놨으시 확인 부탁드립니다.
추가로 요구사항에 대해 작성도 부탁드려요!

2023-06-18 00:18 UTC, graygreat commented on src/main/java/Car.java
> +    private double randomNumber;
자동차가 randomNumber에 대해서 알고 있을 필요가 있을까요?
만약 랜덤 게임이 아니라면요? 그럼 이 코드를 수정해야할 것 같네요.

2023-06-18 00:18 UTC, graygreat commented on src/main/java/Car.java
> +    private static final double INITIAL_RANDOM_NUMBER = -1;
double로 선언하신 이유는?

2023-06-18 00:18 UTC, graygreat commented on src/main/java/Car.java
> +    public void setRandomNumber(double randomNumber) {
set을 사용하신 이유는 있으실까요?

2023-06-18 00:18 UTC, graygreat commented on src/main/java/Car.java
> +        this.location = 1;
1을 상수화 해놓지 않은 이유가 있을까요?

2023-06-18 00:18 UTC, graygreat commented on src/main/java/CarFactory.java
> +    private final RandomNumberFactory factory = new RandomNumberFactory();
여기도 동일하게 Random 게임이 아닌 경우 이 코드를 수정해야겠네요.

2023-06-18 00:18 UTC, graygreat commented on src/main/java/CarFactory.java
> +public class CarFactory {
클래스명을 보곤 이 객체가 무슨 역할을 하는지 모르겠어요

2023-06-18 00:18 UTC, graygreat commented on src/main/java/Filter.java
> +public class Filter {
filter랑 validate랑 차이가 무엇일까요?

2023-06-18 00:18 UTC, graygreat commented on src/main/java/GameStarter.java
> +    private final InputView inputView = new InputView();
GateStarter가 너무 많은걸 의존하고 있는 상태인 것 같아요

2023-06-18 00:18 UTC, graygreat commented on src/main/java/Filter.java
> +        return number > 0;
상수를 하드코딩 하는 것과 private static final로 선언하는건 무슨 차이가 있나요?

2023-06-18 00:18 UTC, graygreat commented on src/main/java/GameStarter.java
> +    public static List<Car> carList = new ArrayList<>();
일급 컬렉션에 대해서 알아보실래요?

2023-06-18 00:18 UTC, graygreat commented on src/main/java/CarFactory.java
> +            GameStarter.carList.add(car);
Game 팩토리가 main을 의존하고 있는데 좋은 구조가 아닌 것 같아요.

2023-06-18 00:18 UTC, graygreat commented on src/main/java/RandomNumberFactory.java
> +        return (Math.random()*10000)%10;
띄어쓰기 잘 해주세요

2023-06-18 00:18 UTC, graygreat commented on src/main/java/ResultView.java
> +public class ResultView {
해당 객체도 싱글톤으로!

2023-06-18 00:18 UTC, graygreat commented on src/test/java/CarTest.java
> +    void CarTest1() {
1, 2, 3보다 더 좋은 메소드명이 있을거에요

2023-06-18 00:18 UTC, graygreat commented on src/test/java/CarTest.java
> +        RandomNumberFactory factory = new RandomNumberFactory();
저흰 이동하는 방법을 랜덤 게임이 아니라 팀 내부에서 정할게요! 라고 하면 테스트 코드를 수정해야겠네요 ㅠ

2023-06-18 00:18 UTC, graygreat commented on src/test/java/CarTest.java
> +public class CarTest {
해당 테스트 코드에도 예외가 있을 수 있을 것 같은데 예외 테스트 작성해주세요.

2023-06-18 00:18 UTC, graygreat commented on src/test/java/InputViewTest.java
> +    public  byte[] intToByteArray(int value) {
이렇게 해주는 이유가 있을까요?

2023-06-18 00:18 UTC, graygreat commented on src/main/java/InputView.java
> +public class InputView {
싱글톤은 무엇일까요?
해당 객체를 싱글톤으로 만들어보는건 어떨까요?

2023-06-18 00:18 UTC, graygreat commented on src/test/java/CarTest.java
> +public class CarTest {
https://www.baeldung.com/parameterized-tests-junit-5

이 글을 보고 테스트 코드를 다시 한번 작성해보시죠

2023-06-20 04:55 UTC, piedra-de-flor commented on src/main/java/Car.java
> +    private double randomNumber;
Stream를 사용하여 처리하려고 노력하다 보니 책임 분배에 실패한것 같습니다, 책임을 나누는 과정부터 다시 고민해보겠습니다.

2023-06-20 04:57 UTC, piedra-de-flor commented on src/main/java/Car.java
> +    private static final double INITIAL_RANDOM_NUMBER = -1;
randomNumber는 0~10 사이의 난수를 저장하는 변수인데, 정수값으로도 받을 수 있었지만 0~10사이의 난수라는 개념에는 정수의 범위보다는 실수의 범위가 더 어울리는거 같아 double로 선언하였습니다.

2023-06-20 05:04 UTC, piedra-de-flor commented on src/main/java/Car.java
> +    public void setRandomNumber(double randomNumber) {
car 변수가 가지고 있는 변수인 randomNumber는 차량의 전진을 결정하는 중요한 속성이기 때문에 외부에서 함부로 변경하거나 값을 삽입해서는 안된다고 판단했기에 변수 randomNumber를 private로 선언하였고, 전형적인 캡슐화의 방식에 따라 private 속성의 값에 접근할 수 있는 set 메서드를 사용하였습니다

2023-06-20 05:04 UTC, piedra-de-flor commented on src/main/java/Car.java
> +        this.location = 1;
음..제 코드에서는 상수화를 시켜놨는데 커밋이 잘 안된거 같네요....ㅠㅠ

2023-06-20 05:05 UTC, piedra-de-flor commented on src/main/java/CarFactory.java
> +    private final RandomNumberFactory factory = new RandomNumberFactory();
넵, random 게임이 아닌경우에는 RandomNumberFactory 클래스 자체를 삭제시키는 방향으로 수정할거 같습니다

2023-06-20 05:08 UTC, piedra-de-flor commented on src/test/java/CarTest.java
> +    void CarTest1() {
@DisplayName을 사용해서 메서드명을 신경 안썼습니다, 메서드명 수정하겠습니다!

2023-06-20 05:12 UTC, piedra-de-flor commented on src/test/java/CarTest.java
> +        RandomNumberFactory factory = new RandomNumberFactory();
음....제가 이 리뷰에 대해서는 잘 이해를 못한거 같습니다 ㅠㅠ

2023-06-20 05:13 UTC, piedra-de-flor commented on src/test/java/CarTest.java
> +public class CarTest {
넵 테스트 코드 다시 작성해보겠습니다!

2023-06-20 05:19 UTC, piedra-de-flor commented on src/test/java/InputViewTest.java
> +    public  byte[] intToByteArray(int value) {
Scanner를 사용하여 입력값을 받아서 사용하기 때문에 Scanner에 어떤 입력값을 넣을 것인지에 대해 Test코드에서 처리해야 했습니다, 
열심히 구글링 해본 결과 InputStream을 사용하면 Scanner에 넣어질 값을 지정할 수 있었고 이 InputStream은 ByteArray형식의 데이터를 처리할 수 있었습니다.

제가 원하는 입력값은 정수 타입의 변수였지만 primitive 타입인 int 에는 byte로 변환해주는 getBytes() 메서드를 찾을 수 없었고, 그래서 int 형 타입을 Byte배열로 바꿔주기 위해 메서드를 작성했습니다

하지만 결국 입력값으로 String을 받기로 결정했고, 이제 사용하지 않는 메서드인데 삭제를 못시킨거 같습니다.
삭제 시키겠습니다.

2023-06-20 05:21 UTC, piedra-de-flor commented on src/main/java/InputView.java
> +public class InputView {
싱글톤이란 클래스에 대한 인스턴스를 하나만 생성하고 다른 인스턴스 생성을 못하게 하여 메모리 낭비를 줄여주는 장점이 있는 디자인 패턴입니다.
싱클톤 패턴을 사용하도록 리팩터링 해보겠습니다.

2023-06-20 05:46 UTC, piedra-de-flor commented on src/main/java/CarFactory.java
> +public class CarFactory {
클래스명을 좀 더 명확하게 수정시키겠습니다

2023-06-20 05:56 UTC, piedra-de-flor commented on src/main/java/Filter.java
> +public class Filter {
validate는 유효성을 뜻합니다, 유효성이라는 개념은 어떤 객체의 어떤 속성을 검사하느냐에 따라 구현의 차이가 있어야 하기에 validate를 하위 개념으로 두고 validate를 검사해주는 상위 개념으로 filter를 사용했습니다.

먼저 초기 설계를 할 때에는 Filter 라는 인터페이스를 두고 원하는 유효성 검사가 필요할 때 마다 filter 인터페이스를 implement한 filter를 만들어 사용하도록 하고 싶었습니다 ex) carFilter, inputFilter...etc

하지만 설계가 부족했는지 구현함에 있어 어려움이 있어 구현하지 못한점 또한 filter랑 validate 차이를 명확하게 하지 못한 이유인것 같기도 합니다.

2023-06-20 05:56 UTC, piedra-de-flor commented on src/main/java/GameStarter.java
> +    private final InputView inputView = new InputView();
제가 가장 리팩터링 하고 싶은 부분이 이부분입니다....
저도 GameStarter의 책임이 역할에 비해 너무 많다고 생각했지만 어떻게 나누어야할지 아직 갈피를 못잡고 있는 상태입니다 ㅠㅠ 고민해서 리팩터링 해보겠습니다

2023-06-20 05:59 UTC, piedra-de-flor commented on src/main/java/Filter.java
> +        return number > 0;
하드코딩을 하게 될 경우에는 변수의 의미를 파악하기 힘들고 유지보수에도 어려움이 있을 수 있습니다.
따라서 변수를 상수화 시켜줌으로써 의미를 정확하게 하고 유지보수에서의 장점또한 챙겨 갈 수 있습니다.

지금 보니 매직넘버가 몇몇 남아있네요 전부 상수화 시키겠습니다.

2023-06-20 05:59 UTC, piedra-de-flor commented on src/main/java/GameStarter.java
> +    public static List<Car> carList = new ArrayList<>();
넵 일급 컬렉션에 대해서는 공부해보겠습니다.

2023-06-20 06:01 UTC, piedra-de-flor commented on src/main/java/CarFactory.java
> +            GameStarter.carList.add(car);
static으로 선언이 된 리스트(변수)를 사용하는 것도 의존관계에 있다는 것을 알지 못했던 것 같습니다.
의존 관계를 줄여보겠습니다.

2023-06-20 06:01 UTC, piedra-de-flor commented on src/main/java/RandomNumberFactory.java
> +        return (Math.random()*10000)%10;
ㅎㅎ...죄송합니다....

2023-06-20 06:02 UTC, piedra-de-flor commented on src/main/java/ResultView.java
> +public class ResultView {
싱글톤 패턴으로 리팩터링 해보겠습니다.

2023-06-20 06:34 UTC, graygreat requested changes
추가로 리뷰 작성했습니다~

확인 부탁드려요!

2023-06-20 06:34 UTC, graygreat commented on src/main/java/Car.java
> +    private static final double INITIAL_RANDOM_NUMBER = -1;
0이 아닌 -1로 초기화 하신 경우가 있나요?
승리해도 0부터 시작할 것 같은데요

2023-06-20 06:34 UTC, graygreat commented on src/main/java/Car.java
> +    public void setRandomNumber(double randomNumber) {
지금 Car 객체가 아닌 다른 객체에서 set 메소드를 사용해서 randomNumber의 값을 조정하고 있는데, 캡슐화가 깨진 것 아닌가요?

2023-06-20 06:34 UTC, graygreat commented on src/main/java/InputView.java
> +        return scanner.nextInt();
현재 숫자가 아닌 값이 들어오면 어떻게 될까요?
어떻게 해결해볼 수 있을까요?

2023-06-20 06:34 UTC, graygreat commented on src/main/java/CarFactory.java
> +    private final RandomNumberFactory factory = new RandomNumberFactory();
random 게임이 아닌 경우 그럼 CarFactory에 있는 코드들도 수정해야하는데, 하나의 이유 때문에 변경될 코드가 많아지는 것 아닐까요?

2023-06-20 06:34 UTC, graygreat commented on src/main/java/Filter.java
> +public class Filter {
굳이 필터로 따로 뺄 이유가 있을까요?

2023-06-20 06:34 UTC, graygreat commented on src/main/java/Filter.java
> +    public boolean CheckInputValidate(int number) {
메소드명이 명확하지 않은 것 같아요.
처음 보는 사람이 이걸 보면 왜 0 이상이지 생각이 들거같네요.

2023-06-20 06:34 UTC, graygreat commented on src/main/java/Filter.java
> +        return randomNumber >= 4;
얘도 동일하게 메소드명이 명확하지 않은 것 같아요.
처음 보는 사람이 이걸 보면 왜 4 이상이지 생각이 들거같네요.

2023-06-20 06:34 UTC, graygreat commented on src/main/java/GameStarter.java
> +        System.out.println();
얘도 view 담당하는 곳으로 옮기면 좋겠네요.

2023-06-20 06:34 UTC, graygreat commented on src/test/java/CarTest.java
> +        RandomNumberFactory factory = new RandomNumberFactory();
기획자분이 "영우님, 저희 이번 프로젝트 랜덤 게임이 아니라 자체적으로 팀 내부에서 숫자 지정하는 방식으로 변경할게요" 라고 한다면 테스트 코드를 다 수정해야하지 않을까요?

2023-06-20 06:34 UTC, graygreat commented on src/test/java/ResultViewTest.java
> +        OutputStream realResult = new ByteArrayOutputStream();
print 하는 것에 대해 테스트 하는게 의미 있을까요?

2023-06-20 06:39 UTC, piedra-de-flor commented on src/main/java/Car.java
> +    private static final double INITIAL_RANDOM_NUMBER = -1;
음...생각해보니 굳이 -1로 초기화 할 이유가 없네요.
0으로 리팩터링 해야할거 같습니다

2023-06-20 06:43 UTC, piedra-de-flor commented on src/main/java/Car.java
> +    public void setRandomNumber(double randomNumber) {
리뷰를 보니 setter와 getter는 캡슐화에 적합하지 않다는 글을 본 기억이 납니다.
setter getter를 사용하지 않고 캡슐화가 되도록 리팩터링 해보겠습니다.

2023-06-20 06:45 UTC, piedra-de-flor commented on src/main/java/CarFactory.java
> +    private final RandomNumberFactory factory = new RandomNumberFactory();
음 맞는 말씀이신데, 제가 이 부분에 대해서는 어떻게 리팩터링을 진행해야 할지 아직 잘 모르겠습니다ㅠㅠ

2023-06-20 06:47 UTC, piedra-de-flor commented on src/main/java/Filter.java
> +public class Filter {
초기에 역할을 나눌 때 유효성을 검사하는 기능 또한 하나의 역할로 생각하고 설계를 했습니다.
그래서 유효성 검사를 검사 대상 속성을 가진 객체 스스로 해도 되지만 저는 하나의 책임으로 분할하였습니다.

2023-06-20 06:50 UTC, piedra-de-flor commented on src/test/java/CarTest.java
> +        RandomNumberFactory factory = new RandomNumberFactory();
음...그렇네요 테스트 코드는 코드 수정이 필요할시 유연하게 대처가 가능해야 하는데 제 테스트 코드는 유연성이 떨어지는것 같습니다 한번 리팩터링 진행해보겠습니다.

2023-06-20 06:54 UTC, piedra-de-flor commented on src/main/java/InputView.java
> +        return scanner.nextInt();
일단 숫자가 아닌 값이 들어오거나 int 범위 밖의 수를 입력할 시에는 InputMismatchException이 발생할 것으로 보입니다.
이에 대한 예외처리를 하면 해결할 수 있을 것 같습니다.

2023-06-20 06:54 UTC, piedra-de-flor commented on src/main/java/Filter.java
> +    public boolean CheckInputValidate(int number) {
넵 메서드명 수정하겠습니다.

2023-06-20 06:55 UTC, piedra-de-flor commented on src/main/java/Filter.java
> +        return randomNumber >= 4;
매직넘버를 수정함으로써 메서드 기능의 명확도를 높혀줄 수 있을거 같습니다.
매직넘버 상수화 처리, 메서드 이름 변경하겠습니다

2023-06-20 06:56 UTC, piedra-de-flor commented on src/main/java/GameStarter.java
> +        System.out.println();
음 이건 정말 저도 왜 저기에 선언했는지 모르겠네요ㅠㅠ 수정하겠습니다

2023-06-20 07:03 UTC, piedra-de-flor commented on src/test/java/ResultViewTest.java
> +        OutputStream realResult = new ByteArrayOutputStream();
초기에는 몇번의 전진 시도 후 Car 객체의 전진을 잘했고 위치가 잘바뀌었나를 테스트하고 싶었으나,
random의 난수값에 따라 전진을 할지 말지를 결정하기 때문에 비교하고자 하는 Car 객체가 현재 어떤 location값을 가지고 있어야 할지 개발자인 저조차도 예측할 수 가 없었습니다.

물론 제가 임의로 난수값을 조정해 Car의 위치를 정할 수 있겠지만, 그렇게 테스트 코드를 작성하기 보다 콘솔창의 output을 비교하는 테스트 코드가 더 간결하다고 생각했기에 위 테스트를 작성했습니다.

2023-06-20 07:32 UTC, graygreat requested changes

2023-06-20 07:32 UTC, graygreat commented on src/main/java/CarFactory.java
> +    private final RandomNumberFactory factory = new RandomNumberFactory();
한번 고민해보시죠~

2023-06-20 07:32 UTC, graygreat commented on src/main/java/InputView.java
> +        return scanner.nextInt();
예외가 발생하면 IllegalArgumentException을 던져보도록 해보세요!

2023-06-20 07:32 UTC, graygreat commented on src/main/java/InputView.java
> +        System.out.println("시도할 횟수는 몇 회인가요?");
이것들도 사실 다 OutView의 책임이지 않을까요?

2023-06-20 07:32 UTC, graygreat commented on src/test/java/ResultViewTest.java
> +        OutputStream realResult = new ByteArrayOutputStream();
print를 찍어주는걸 테스트 하는건 사실 자바 자체를 테스트 하고 있다고 볼 수 있어요.
아래 로직을 테스트 하는게 의미가 있을까요?

```java=
for (int i = 0; i < 5; i++) {
  System.out.print("-")
}
```

2023-06-23 16:22 UTC, merged