java-racingcar 1.5
piedra-de-flor/java-racingcar pull request #2
Opened 2023-06-24 19:22 UTC by piedra-de-flor

2023-06-25 01:16 UTC, graygreat requested changes

2023-06-25 01:16 UTC, graygreat commented on src/main/java/cars/Car.java
> +    Car() {
public 접근 지정자를 붙인 것과 붙이지 않은 것이 있는데, 어떠한 차이가 있나요?

2023-06-25 01:16 UTC, graygreat commented on src/main/java/cars/CarManager.java
> +    private final List<Car> carList;
일급 컬렉션에 대해서 공부해보시죠

2023-06-25 01:16 UTC, graygreat commented on src/main/java/cars/CarMoveByRandomNumberManager.java
> +        IntStream.range(0, getCarList().size())
0도 매직 넘버네요.

2023-06-25 01:16 UTC, graygreat commented on src/main/java/cars/CarObjectMaker.java
> +public class CarObjectMaker {
일급 컬렉션을 만들면 이 객체는 필요없어질 것 같네요.

2023-06-25 01:16 UTC, graygreat commented on src/main/java/game/InputView.java
> +    private static final InputView inputView = new InputView();
해당 로직도 상수화 시켜준거니 대문자로 해주면 좋지않을까요?

2023-06-25 01:16 UTC, graygreat commented on src/main/java/game/InputView.java
> +    public void input() {
[수직 거리](https://nesoy.github.io/articles/2018-01/CleanCode-Form)에 대해서 한번 알아보시죠

2023-06-25 01:16 UTC, graygreat commented on src/test/java/CarTest.java
> +                .filter(car -> car.getClass().equals(Car.class))
이건 무엇을 검증하는건가요?

2023-06-25 01:16 UTC, graygreat commented on src/test/java/CarTest.java
> +        assertThat(testManager.getCarList().stream()
검증 로직을 작성하는데 굳이 stream을 사용할 필요가 있나 생각이 드네요.

2023-06-25 01:16 UTC, graygreat commented on src/test/java/InputViewTest.java
> +        assertThat(false).isEqualTo(InputView.getInstance().validateInput(-1, -1));
https://www.baeldung.com/parameterized-tests-junit-5

이거 봐보시고 바꿔보시죠.

2023-06-25 01:16 UTC, graygreat commented on src/main/java/game/InputView.java
> +            throw new IllegalArgumentException();
예외가 발생했을 때, 메시지도 같이 던져주면 좋을 것 같네요.

2023-06-25 01:16 UTC, graygreat commented on src/main/java/game/InputView.java
> +        try {
위 로직과 중복되네요.

2023-06-27 05:40 UTC, piedra-de-flor commented on src/main/java/cars/Car.java
> +    Car() {
캡슐화를 진행하기 위해 public 접근 지정자가 아닌 default로 지정함으로써 Car에 관련된 클래스만 관리하는 cars 패키지 내에서만 접근이 가능하도록 하였습니다. 
Car 클래스의 생성자는 CarObjectMaker에서만 사용하기 때문에 carList를 일급컬렉션으로 변경하면 캡슐화를 더 고도화 시킬 수 있을거 같습니다.

2023-06-27 05:40 UTC, piedra-de-flor commented on src/main/java/cars/CarMoveByRandomNumberManager.java
> +        IntStream.range(0, getCarList().size())
매직넘버 상수화 처리 하겠습니다!

2023-06-27 05:41 UTC, piedra-de-flor commented on src/main/java/cars/CarManager.java
> +    private final List<Car> carList;
넵....

2023-06-27 05:41 UTC, piedra-de-flor commented on src/main/java/cars/CarObjectMaker.java
> +public class CarObjectMaker {
일급 컬렉션을 사용해서 리펙러팅 진행해보겠습니다!

2023-06-27 05:42 UTC, piedra-de-flor commented on src/main/java/game/InputView.java
> +    private static final InputView inputView = new InputView();
final이 붙어서 상수화가 된걸 인지하지 못했네요. 바로 변경하겠습니다.

2023-06-27 05:42 UTC, piedra-de-flor commented on src/main/java/game/InputView.java
> +    public void input() {
넵 공부해보겠습니다!!

2023-06-27 05:44 UTC, piedra-de-flor commented on src/test/java/CarTest.java
> +                .filter(car -> car.getClass().equals(Car.class))
carList를 생성했을때 null값 혹은 car 객체가 아닌 다른 무엇이 들어있는지 검사하는 코드인데 과연 이 테스트가 필요할까 고민하긴 했지만 작성해놓은 테스트 코드를 굳이 지울 필요는 없다고 생각했습니다 ㅜㅜ

2023-06-27 05:45 UTC, piedra-de-flor commented on src/test/java/CarTest.java
> +        assertThat(testManager.getCarList().stream()
하핳...stream이랑 람다를 공부하면서 많이 써보고 싶다는 생각 탓에 자주 사용한거 같습니다...!

2023-06-27 05:45 UTC, piedra-de-flor commented on src/main/java/game/InputView.java
> +            throw new IllegalArgumentException();
예외 메세지 추가하겠습니다

2023-06-27 05:45 UTC, piedra-de-flor commented on src/test/java/InputViewTest.java
> +        assertThat(false).isEqualTo(InputView.getInstance().validateInput(-1, -1));
열심히 해석해가면서 읽어보는 중인데 쉽지않네요. 수요일 전까지 다 읽고 고쳐놓겠습니다.

2023-06-27 05:46 UTC, piedra-de-flor commented on src/main/java/game/InputView.java
> +        try {
음 기능별로 나누다 보니 중복된 코드가 생겼네요 바로 메서드 추출하겠습니다!

2023-07-04 12:37 UTC, graygreat requested changes

2023-07-04 12:37 UTC, graygreat commented on README.md
> +### 🧾 비지니스 로직
기능 목록에 대해서 작성해주시면 더 좋을 것 같아요.
지금은 개발에 대한 요구사항들을 작성했는데, 어떠한 기능이 구현되는지 개발자가 안닌 사람도 읽을 수 있으면 좋을 것 같네요.

2023-07-04 12:37 UTC, graygreat commented on src/main/java/cars/CarList.java
> +public class CarList {
타입이 객체명에 있는건 좋지 않는 네이밍 인 것 같네요

2023-07-04 12:37 UTC, graygreat commented on src/main/java/cars/CarList.java
> +        makeCarList(carList);
클린 코드 수직거리에 대해서 한번 봐보시죠

2023-07-04 12:37 UTC, graygreat commented on src/main/java/cars/CarList.java
> +        return Collections.unmodifiableList(carList);
unmodifiableList을 사용하신 이유가 있을까요?

2023-07-04 12:37 UTC, graygreat commented on src/main/java/cars/CarList.java
> +        for (int aCar = 0; aCar < InputView.getInstance().getCarNumber(); aCar++) {
aCar는 무슨 뜻인가요?

2023-07-04 12:37 UTC, graygreat commented on src/main/java/cars/CarList.java
> +        for (int aCar = 0; aCar < InputView.getInstance().getCarNumber(); aCar++) {
CarList에서 InputView를 의존하고 있는게 맞는 구조일까요?

2023-07-04 12:37 UTC, graygreat commented on src/main/java/cars/CarManager.java
>  public abstract class CarManager {
해당 객체의 역할이 무엇인가요?
Car의 일급 컬렉션과 역할이 많이 겹치는 것 같은데요.

2023-07-04 12:37 UTC, graygreat commented on src/main/java/cars/RandomNumberFactory.java
> +    private final int MULTIPLE_NUMBER_FOR_RANDOM_NUMBER_BETWEEN_0_TO_10 = 10;
MULTIPLE_NUMBER_FOR_RANDOM_NUMBER_BETWEEN_0_TO_10

이걸 보고 무슨 변수인지 예상이 안되네요.

2023-07-04 12:37 UTC, graygreat commented on src/main/java/cars/CarMoveByRandomNumberManager.java
>  public class CarMoveByRandomNumberManager extends CarManager {
해당 객체가 필요한가요?
RandomNumberFactory를 추상화해서 CarManager에서 사용하면 되지 않을까 싶은데 어떻게 생각하시나요?

2023-07-04 13:43 UTC, piedra-de-flor commented on src/main/java/cars/CarList.java
> +        return Collections.unmodifiableList(carList);
일급 컬렉션의 주요 기능은 아니지만, 불변을 표현하기 위해 사용하였습니다.
setter메서드가 없어도 충분히 변화를 줄 수 있기에 Collection을 read-only로 만들어주는 unmodifiableList를 사용하였습니다.

2023-07-04 13:45 UTC, piedra-de-flor commented on src/main/java/cars/CarList.java
> +        for (int aCar = 0; aCar < InputView.getInstance().getCarNumber(); aCar++) {
자바의 신이었는지 개구리 책이었는지 기억은 잘 안나지만 변수명 앞에 a를 붙혀 변수를 표현하는 분도 계신다는걸 알게 되었고, for문 안에 int i 가 너무 보기 싫어서 car의 순서를 의미할 수 있는 적당한 변수명이 뭐가 있을까 고민하다가 aCar로 선언하게 되었습니다.

2023-07-04 13:46 UTC, piedra-de-flor commented on src/main/java/cars/CarList.java
> +        for (int aCar = 0; aCar < InputView.getInstance().getCarNumber(); aCar++) {
의존성 제거 하여서 다시 푸시하겠습니다!

2023-07-04 14:05 UTC, piedra-de-flor commented on src/main/java/cars/CarList.java
> +public class CarList {
rename 했습니다!

2023-07-04 17:05 UTC, piedra-de-flor commented on src/main/java/cars/RandomNumberFactory.java
> +    private final int MULTIPLE_NUMBER_FOR_RANDOM_NUMBER_BETWEEN_0_TO_10 = 10;
네이밍 다시 작성했습니다.

2023-07-04 17:32 UTC, piedra-de-flor commented on src/main/java/cars/CarMoveByRandomNumberManager.java
>  public class CarMoveByRandomNumberManager extends CarManager {
RandomNu,berFactory를 새로 CarFilter라는 인터페이스로 추상화 시켜서 CarManager에서 사용하도록 리팩터링했습니다!

2023-07-04 17:40 UTC, piedra-de-flor commented on src/main/java/cars/CarManager.java
>  public abstract class CarManager {
Car의 일급 컬렉션은 말 그대로 컬렉션을 다루기 위함입니다.
Car객체를 담아주는 List을 특정 로직에 맞게 생성하고 관리할 뿐이며 그에 비해 
CarManager객체의 경우에는 일급 컬렉션을 직접적으로 사용하는 객체입니다.
즉 역할의 차이로 말씀드리자면, 
Car의 일급 컬렉션은 정해진 조건에 맞게 Car 객체를 생성하여 List에 보관 및 관리하는 역할,
CarManager는 그 List를 사용하여 직접적인 로직을 수행하는 역할입니다.

2023-07-06 10:24 UTC, merged